apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors-v2
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-sensors-v2
spec:
  source:
    git:
      url: https://github.com/trevorputbrese/spring-sensors-v2.git
      ref:
        branch: master
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1

